dist: focal
language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
env:
  - DJANGO_VERSION=3.2
  - DJANGO_VERSION=4.0
# command to install dependencies
install:
  - pip install django~=$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install python-coveralls coverage
# command to run tests
script:
  - coverage run --source='qr_code' manage.py test
after_success:
  - coveralls
