language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.10.7
  - DJANGO_VERSION=1.11.7
# command to install dependencies
install:
  - pip install django~=$DJANGO_VERSION
  - pip install -r requirements.txt
# command to run tests
script: python manage.py test