name: Django QR Code Build and Test

on:
  push:
    branches:
    - master
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-22:04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run tests
      run: |
        cd scripts
        ./run-tests.sh
      
